### ISSUE TITLE
xboot smp_processor_id() returns always 5.

### ISSUE THREAD

**Issue by gadget114514** [xboot/xboot#16]
I use xboot master on lichee nano (f1c100s).
xboot smp_processor_id() returns always 5. maybe it should return 0.
i don't know how to fix it. can i have a hint to fix?

**Comment by jerryjianjun** [comment]
Yes, It's a issues, This commit fix it, Please check!
https://github.com/xboot/xboot/commit/ae0545477901c44c06f73c86442ec39a9d533d6b
