### ISSUE TITLE
Does xboot require proprietary blobs for Exynos4412?

### ISSUE THREAD

**Issue by herbsmn** [xboot/xboot#19]
Hello,

All u-boot ports for the Exynos4412 that I have seen require a proprietary blob for BL1, and many of them also require a proprietary blob for BL2. I'm not seeing any blobs in your 4412 code. Is this because a proprietary blob isn't needed?

-herbsmn

**Comment by herbsmn** [comment]
Is this is the BL1 blob? https://github.com/xboot/xboot/blob/master/src/arch/arm32/mach-exynos4412/tools/linux/mk4412

**Comment by jerryjianjun** [comment]
XBOOT just as a bl1 and no bl2, bl3..., The key code
`	/* Copyself to link address */
	adr r0, _start
	ldr r1, =_start
	cmp r0, r1
	beq 1f
	bl sys_copyself
1:	nop`

mk4412 just a fix header tool for irom booting

**Comment by herbsmn** [comment]
I don't understand your response. Can you say more about this?

**Comment by herbsmn** [comment]
Can you please say more, @jerryjianjun?
