### ISSUE TITLE
Translate to english language

### ISSUE THREAD

**Issue by rprata** [xboot/xboot#3]
Hi, 
Congratulations on your project. However, I would like to test, but the README and site information is in Chinese. Is it possible to create a English Version? I could you help to translate it.

Best Regards,

**Comment by jerryjianjun** [comment]
yes, of course, please fork and pull request

**Comment by jerryjianjun** [comment]
add some commit for english language, plese help me.
https://github.com/xboot/xboot/blob/master/README.md#xboot-introduction
https://github.com/xboot/xboot/blob/master/documents/xboot-system-development-guide-en-US.md

**Comment by rprata** [comment]
Ok, I'll help you.

**Comment by jerryjianjun** [comment]
thanks
