### ISSUE TITLE
task_self 函数存在可能返回空的情况，可能会导致内存非法访问

### ISSUE THREAD

**Issue by juiceRv** [xboot/xboot#31]
https://github.com/xboot/xboot/blob/0c4ffd20d2e14e353ab2f3818eadeaa7989b6f43/src/kernel/core/mutex.c#L43-L50

在这个函数里没有经过检查self的地址是否合法就直接使用了，存在允许导致内存非法访问的情况存在！

**Comment by juiceRv** [comment]
https://github.com/xboot/xboot/blob/0c4ffd20d2e14e353ab2f3818eadeaa7989b6f43/src/kernel/core/mutex.c#L43-L50

**Comment by jianjunjiang** [comment]
进入main函数后，第一时间创建init进程，这样task_self就不会存在空指针的情况了
# 7abfaab0062f7bbb790aec5bb6f21f8bec4f2041
