### ISSUE TITLE
BUG 

### ISSUE THREAD

**Issue by tao-eternal** [xboot/xboot#37]
![image](https://user-images.githubusercontent.com/30024821/152650521-06c9e93e-f92d-43cf-a19a-7ef3002bc936.png)
![image](https://user-images.githubusercontent.com/30024821/152650634-b830c7d1-c999-463f-8cc0-7a0f43b0ac94.png)
As you see, this file has an incompatible name.
Please give a fix to delete the `white space`.

**Comment by jianjunjiang** [comment]
https://github.com/xboot/xboot/commit/c5245e96b994eed6506079a22a2521973d2243d3
This patch fix it!
