### ISSUE TITLE
Porting for ODROID  C2

### ISSUE THREAD

**Issue by rprata** [xboot/xboot#5]
Hi, all,

Is there a porting this xboot for Odroid? If so, could you share the document with these instructions (a how to compile and burn on this platform).

Best regards,

**Comment by jerryjianjun** [comment]
ODROID C2, The soc is amlogic s905, not yet support, list some platform supported:

| directory            | description                                      |
| ------------- | --------------------------------------- |
| mach-apple    | apple A4 cpu，Iphone4，Ipod touch 4g，Ipad 1g |
| mach-h3       | allwinner H3，Nano PI                          |
| mach-n3ds     | 3DS，New 2DSXLL                  |
| mach-raspi2   | Raspberry PI 2                         |
| mach-realview | Qemu Realview                        |
| mach-v3s      | allwinner V3S，Lichee PI Zero                  |
| mach-x3128    | rockchip RK3128                               |
| mach-x3288    | rockchip RK3288                               |
| mach-x4418    | samsung S5P4418                               |

| directory          | description              |
| ----------- | --------------- |
| mach-raspi3 | Raspberry PI 3 |
| mach-virt   | Qemu Virt    |
| mach-x3399  | rockchip RK3399       |
| mach-x6818  | samsung S5P6818       |

**Comment by jerryjianjun** [comment]
In the git repository, some of the older BSP packages have been removed, including s5p6410 s5pv210 exynos4412 etc

**Comment by rprata** [comment]
Ok. I want to start a project to create this porting. Is there a document with recommendations to start that (how to organize this kind of project)?

**Comment by jerryjianjun** [comment]
see this link
https://github.com/xboot/xboot/blob/master/documents/xboot-system-development-guide-en-US.md
